apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quotes-student-15
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: student-15
  project: default
  source:
    repoURL: https://github.com/lribeiro-eficode/argocd-katas  # Update this URL if the helm chart is in a different repo
    targetRevision: HEAD
    path: quotes-flask/helm/quotes-flask
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true